const fs = require('fs');
const path = require('path');
const mongoose = require('mongoose');
const { Product } = require('../api/models');
require('dotenv').config({ path: '../api/.env' });

async function upgradeManifests() {
    try {
        await mongoose.connect(process.env.MONGODB_URI);
        const products = await Product.find({}).populate('category');
        const root = path.join(__dirname, '../assets_master/products');

        const categories = fs.readdirSync(root);
        for (const cat of categories) {
            const catPath = path.join(root, cat);
            if (!fs.statSync(catPath).isDirectory()) continue;

            const prods = fs.readdirSync(catPath);
            for (const prodFolder of prods) {
                const prodPath = path.join(catPath, prodFolder);
                if (!fs.statSync(prodPath).isDirectory()) continue;

                const match = products.find(p => p.name.trim() === prodFolder.trim());
                if (match) {
                    // 1. Delete old details.txt
                    const oldFile = path.join(prodPath, 'details.txt');
                    if (fs.existsSync(oldFile)) fs.unlinkSync(oldFile);

                    // 2. Create README.md (Rich Human Readable)
                    const images = fs.readdirSync(prodPath).filter(f => /\.(jpe?g|png|webp)$/i.test(f));
                    const mainImg = images.find(img => img.includes('_1.')) || images[0];

                    const readme = [
                        `# 📦 ${match.name}`,
                        `**SKU:** \`${match.sku}\` | **Segment:** \`${match.segment || 'Standard'}\` | **Category:** \`${match.category?.name || cat}\``,
                        `\n## 🛠️ Specifications`,
                        `| Attribute | Value |`,
                        `| :--- | :--- |`,
                        `| Size | ${match.commonSpecs?.size || 'N/A'} |`,
                        `| Pattern | ${match.commonSpecs?.pattern || 'N/A'} |`,
                        `| Rim | ${match.commonSpecs?.rim || 'N/A'} |`,
                        `| Origin | ${match.commonSpecs?.origin || 'N/A'} |`,
                        `| Packing | ${match.packingSize || 'N/A'} |`,
                        `\n## 🔗 Cloud Assets (ImgBB)`,
                        ...(match.media || []).map((url, i) => `- [Asset ${i+1}](${url})`),
                        `\n## 🖼️ Preview`,
                        mainImg ? `![${match.name}](${mainImg})` : `*No image available*`,
                        `\n---`,
                        `*Generated by BTG V3 System on ${new Date().toLocaleDateString()}*`
                    ].join('\n');

                    fs.writeFileSync(path.join(prodPath, 'README.md'), readme);

                    // 3. Create metadata.json (Machine Readable)
                    const metadata = {
                        id: match._id,
                        sku: match.sku,
                        name: match.name,
                        category: match.category?.name,
                        segment: match.segment,
                        specs: match.commonSpecs,
                        packingSize: match.packingSize,
                        cloudMedia: match.media,
                        localFiles: images,
                        lastSync: new Date().toISOString()
                    };

                    fs.writeFileSync(path.join(prodPath, 'metadata.json'), JSON.stringify(metadata, null, 2));
                    console.log(`✨ Upgraded: ${match.sku}`);
                }
            }
        }
        console.log('\n✅ All product manifests upgraded to Industry Standard (README + JSON)');
        process.exit(0);
    } catch (err) {
        console.error('❌ Upgrade failed:', err);
        process.exit(1);
    }
}

upgradeManifests();
